# Use the official PostgreSQL image from the Docker Hub
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=insait_database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=ali
