version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: aliseh
      POSTGRES_PASSWORD: aliseh
      POSTGRES_DB: insait_database
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql://ali:ali@db:5432/insait_database'
    depends_on:
      - db
